/*
 * NOTE: This file generates fake tweet data, and is not intended to be part of your implementation.
 * You can safely leave this file untouched, and confine your changes to index.html.
 */

// set up data structures
window.streams = {};
streams.home = [];
streams.users = {};
streams.tags = {};
streams.users.douglascalhoun = [];
streams.users.mracus = [];
streams.users.sharksforcheap = [];
streams.users.shawndrost = [];
window.users = Object.keys(streams.users);

//This boolean determines whether the #newTweetListener should be triggered
//Primary use case is on page load, with the 10 tweets that are generated by the for-loop
//These should just be loaded and do not need to invoke the #newTweetListener
let tweetSchedulerBool = false;
let showNewTweetsBool = true; //This bool allows the user to control if tweets should be paused / resumed

// utility function for adding tweets to our data structures
var addTweet = function(newTweet){
  var username = newTweet.user;
  streams.users[username].push(newTweet);
  streams.home.push(newTweet);

  //If the new tweet has a tag, push it to the streams.tags object
  if(newTweet.tag) {
    let tag = newTweet.tag;
    tag[0] = tag[0].slice(1);               //Remove the # from the first index of the tag array
    if(!streams.tags[tag[0]]) {             //If streams.tags does not have a property for the current tag
      streams.tags[tag[0]] = [];            //Create a property for that tag
    }
    streams.tags[tag[0]].push(newTweet);    //Push the newTweet into streams.tags at the property for that tag
  }
};

// utility function
var randomElement = function(array){
  var randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
};

// random tweet generator
var opening = ['just', '', '', '', '', 'ask me how i', 'completely', 'nearly', 'productively', 'efficiently', 'last night i', 'the president', 'that wizard', 'a ninja', 'a seedy old man'];
var verbs = ['downloaded', 'interfaced', 'deployed', 'developed', 'built', 'invented', 'experienced', 'navigated', 'aided', 'enjoyed', 'engineered', 'installed', 'debugged', 'delegated', 'automated', 'formulated', 'systematized', 'overhauled', 'computed'];
var objects = ['my', 'your', 'the', 'a', 'my', 'an entire', 'this', 'that', 'the', 'the big', 'a new form of'];
var nouns = ['cat', 'koolaid', 'system', 'city', 'worm', 'cloud', 'potato', 'money', 'way of life', 'belief system', 'security system', 'bad decision', 'future', 'life', 'pony', 'mind'];
var tags = ['#techlife', '#burningman', '#sf', 'but only i know how', 'for real', '#sxsw', '#ballin', '#omg', '#yolo', '#magic', '', '', '', ''];

var randomMessage = function(){
  return [randomElement(opening), randomElement(verbs), randomElement(objects), randomElement(nouns), randomElement(tags)].join(' ');
};

// generate random tweets on a random schedule
var generateRandomTweet = function(){
  var tweet = {};
  tweet.user = randomElement(users);
  tweet.message = randomMessage();
  tweet.tag = findHashtag(tweet.message);                 //Returns a tag array if a tag exists within tweet's message
  tweet.created_at = new Date();
  tweet.globalIdx = streams.home.length;                  //Defines tweet # amongst all users
  tweet.localUserIdx = streams.users[tweet.user].length;  //Defines tweet # amongst specific user

  //Variable to hold index for tweets that have tags
  tweet.localTagIdx; //Default value is undefined, for tweets that do not have tags
  if(tweet.tag) {   //If the tweet has a tag
    let tagKey = tweet.tag[0].slice(1); //Assemble the tag's key, which is the first element of the tag array, less the #
    if(tagKey in streams.tags) {        //If the tagKey exists within the streams.tags object
      tweet.localTagIdx = streams.tags[tagKey].length;  //Assign this index the length of that particular tag's array
    } else {
      tweet.localTagIdx = 0;                            //If key doesn't exist, assign localTagIdx a value of 0
    }
  }

  addTweet(tweet);

  if(tweetSchedulerBool) {  //After page has been loaded, this bool will allow the eventListener to fire
    //Create a click event to simulate on the #newTweetListener div and pass along the new tweet in the event object
    let e = jQuery.Event('click');          //1. Declare variable e that represents a 'click' event in jQuery
    e.tweet = tweet;                        //2. Add the newly generated tweet as a property to this event
    jQuery('#newTweetListener').trigger(e); //3. Trigger the click event on #newTweetListener
  }
};

for(var i = 0; i < 10; i++){
  generateRandomTweet();
}

tweetSchedulerBool = true; //Allows the #newTweetListener to fire

var scheduleNextTweet = function(){
  if(showNewTweetsBool) generateRandomTweet();
  setTimeout(scheduleNextTweet, Math.random() * 1500);
};
scheduleNextTweet();

// utility function for letting students add "write a tweet" functionality
// (note: not used by the rest of this file.)
var writeTweet = function(message){
  if(!visitor){
    throw new Error('set the global visitor property!');
  }
  var tweet = {};
  tweet.user = visitor;
  tweet.message = message;
  addTweet(tweet);
};

//This regex was borrowed from stackOverflow and allows a hashtag to be found within a tweet
function findHashtag(message) {
  let hashtagRegex = /#\w*[a-zA-Z]\w*/gm;
  return hashtagRegex.exec(message);
}